'use strict';
const $=id=>document.getElementById(id);let snapshot=null,selected='',stations=[];
const fmt=v=>v==null?'缺少记录':Number(v).toFixed(1);
const date=v=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'未知';
const expired=v=>!v||Date.now()-new Date(v).getTime()>90*60000;
function grade(n){if(n==null)return['缺少记录','#d1d5db'];if(n===0)return['无降雨','#e5e7eb'];if(n<.1)return['微量降雨','#cffafe'];if(n<10)return['小雨','#67e8f9'];if(n<25)return['中雨','#38bdf8'];if(n<50)return['大雨','#2563eb'];if(n<100)return['暴雨','#4f46e5'];if(n<250)return['大暴雨','#9333ea'];return['特大暴雨','#581c87']}
const find=(p,key)=>p?.stations?.find(s=>s.key===key)?.valueMm??null;
function node(tag,text,cls){const el=document.createElement(tag);if(text!=null)el.textContent=text;if(cls)el.className=cls;return el}
function render(){if(!snapshot)return;const p=snapshot.products||{},daily=p['24h'],hourly=p['1h'],old=expired(snapshot.fetchedAt)||expired(daily?.observedAt)||expired(hourly?.observedAt),station=stations.find(s=>s.key===selected);
$('sourceStatus').textContent=snapshot.status==='error'?'采集失败，当前雨情无法确认':old?'真实数据快照 · 部分数据已过期，仅供历史查看':'中央气象台真实降水实况 · 定时采集';$('statusTitle').textContent=snapshot.status==='error'?'数据不可用':old?'请注意观测时效':'降水实况已更新';$('statusMessage').textContent=snapshot.message+' 抓取时间不等于观测时间。';$('collectedAt').textContent='最近采集：'+date(snapshot.fetchedAt)+' · 北京时间';$('observedAt').textContent='1小时产品：'+date(hourly?.observedAt)+(expired(hourly?.observedAt)?'（已过期）':'')+' / 24小时产品：'+date(daily?.observedAt)+(expired(daily?.observedAt)?'（已过期）':'');
const rain1=find(hourly,selected),rain24=find(daily,selected),[level,color]=grade(rain24);$('rain1').textContent=rain1==null?'—':fmt(rain1);$('rain24').textContent=rain24==null?'—':fmt(rain24);$('rain1Period').textContent=hourly?'源标注：'+hourly.sourcePeriod:'1小时产品不可用';$('rain24Period').textContent=daily?'源标注：'+daily.sourcePeriod:'24小时产品不可用';$('stationCount').textContent=daily?daily.stations.length:'—';$('dataAge').textContent=daily?Math.max(0,Math.floor((Date.now()-new Date(daily.observedAt))/60000)):'—';$('stationTitle').textContent=station?station.name+' · 国家级站点降水实况':'站点暂无记录';$('level').textContent=level+(expired(daily?.observedAt)?'（历史快照）':'');$('swatch').style.background=color;$('stationTotal').textContent=rain24==null?'该站在24小时产品中缺少记录':`过去24小时累计 ${fmt(rain24)} mm`;$('stationPeriod').textContent=daily?'源标注统计时段：'+daily.sourcePeriod:'统计时段未知';
$('regionCards').replaceChildren();for(const s of daily?.stations||[]){const[g,c]=grade(s.valueMm),b=node('button',null,'region'),i=node('i'),text=node('span');b.type='button';b.setAttribute('aria-pressed',String(s.key===selected));i.style.background=c;i.setAttribute('aria-hidden','true');text.append(node('strong',s.name),node('small',g+' · '+fmt(s.valueMm)+(s.valueMm==null?'':' mm')));b.append(i,text);b.addEventListener('click',()=>{selected=s.key;$('stationSelect').value=selected;render()});$('regionCards').append(b)}if(!daily?.stations?.length)$('regionCards').append(node('p','未获取四川站点记录，不能判断无降雨。','muted'));renderChart()}
function renderChart(){const history=snapshot.history||[],values=history.map(p=>find(p,selected)),max=Math.ceil(Math.max(5,...values.filter(v=>v!=null))/5)*5;let svg='<title>所选站点最近6个发布时次的1小时实况雨量，缺失值不填零</title>';for(let j=0;j<=4;j++){const y=210-j*42;svg+=`<line x1="46" y1="${y}" x2="650" y2="${y}" stroke="#e8efec" stroke-dasharray="4 5"/><text x="34" y="${y+4}" text-anchor="end">${(max*j/4).toFixed(1)}</text>`}history.forEach((p,i)=>{const x=60+i*580/Math.max(history.length,1),v=values[i],h=v==null?0:v/max*168,label=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(p.observedAt));if(v==null||v===0)svg+=`<text x="${x+23}" y="199" text-anchor="middle">${v==null?'缺失':'0'}</text>`;else svg+=`<rect x="${x}" y="${210-h}" width="46" height="${h}" rx="4" fill="#39a99a"><title>${label}：${v.toFixed(1)} mm</title></rect>`;svg+=`<text x="${x+23}" y="236" text-anchor="middle">${label}</text>`});if(!history.length)svg+='<text x="330" y="110" text-anchor="middle">历史数据不可用</text>';$('chart').innerHTML=svg;$('tableBody').replaceChildren();history.forEach((p,i)=>{const row=node('tr');row.append(node('td',date(p.observedAt)),node('td',fmt(values[i])),node('td',p.sourcePeriod||'产品获取失败'));$('tableBody').append(row)});$('historyRange').textContent=history.length?date(history[0].observedAt)+' 至 '+date(history.at(-1).observedAt)+' · 北京时间':'暂无有效历史数据'}
async function load(){$('refresh').disabled=true;$('refresh').textContent='读取快照…';try{const r=await fetch('data/weather.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP');const d=await r.json();if(d.schemaVersion!==2||d.isDemo!==false||!d.products)throw Error('schema');snapshot=d;const map=new Map();for(const p of Object.values(d.products))for(const s of p.stations||[])map.set(s.key,s);stations=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));$('stationSelect').replaceChildren();if(!stations.length){const o=node('option','暂无站点数据');o.value='';$('stationSelect').append(o)}else{for(const s of stations){const o=node('option',s.name);o.value=s.key;$('stationSelect').append(o)}if(!stations.some(s=>s.key===selected))selected=stations[0].key}$('stationSelect').value=selected;render();$('fetchError').hidden=true}catch{snapshot=null;$('fetchError').hidden=false;$('sourceStatus').textContent='快照读取失败，当前雨情无法确认';$('statusTitle').textContent='数据读取失败';$('statusMessage').textContent='请查看官方原始页面。若下方仍有数字，它们是上次读取的旧快照。'}finally{$('refresh').disabled=false;$('refresh').textContent='重新读取'}}
$('stationSelect').addEventListener('change',()=>{selected=$('stationSelect').value;render()});$('refresh').addEventListener('click',load);$('fontToggle').addEventListener('click',()=>{const active=document.body.classList.toggle('big');$('fontToggle').setAttribute('aria-pressed',String(active));$('fontToggle').textContent=active?'标准字号':'大字模式'});load();setInterval(()=>{if(snapshot)render()},60000);setInterval(load,5*60000);
