'use strict';
let selectedCity='',selectedParent='成都市';
function prepareCities(){
 const regions=snapshot.cityData?.regions||[],parents=[...new Set(regions.map(r=>r.parent))];
 if(!parents.includes(selectedParent))selectedParent=parents[0]||'';
 $('parentSelect').replaceChildren();for(const name of parents){const o=node('option',name);o.value=name;$('parentSelect').append(o)}$('parentSelect').value=selectedParent;
 const local=regions.filter(r=>r.parent===selectedParent);if(!local.some(r=>r.id===selectedCity))selectedCity=local[0]?.id||'';
 $('citySelect').replaceChildren();for(const r of local){const o=node('option',r.name+(r.weatherCode?'':'（未覆盖）'));o.value=r.id;$('citySelect').append(o)}$('citySelect').value=selectedCity;
}
function rainSvg(id,rows,title){
 const width=Math.max(670,rows.length*50+60),max=Math.max(1,...rows.map(r=>r.rainMm||0));let svg='<title>'+title+'</title>';
 for(let j=0;j<=4;j++){const y=200-j*40;svg+=`<line x1="45" y1="${y}" x2="${width-10}" y2="${y}" stroke="#dbe5e1"/><text x="40" y="${y+4}" text-anchor="end">${(max*j/4).toFixed(1)}</text>`}
 rows.forEach((r,i)=>{const x=55+i*(width-70)/Math.max(1,rows.length),h=(r.rainMm||0)/max*160,w=Math.min(32,(width-70)/Math.max(1,rows.length)-8),label=r.label||date(r.at);svg+=r.rainMm==null?`<text x="${x}" y="192">缺</text>`:r.rainMm===0?`<text x="${x}" y="192">0</text>`:`<rect x="${x}" y="${200-h}" width="${w}" height="${h}" rx="3" fill="#38a9bf"><title>${label}：${r.rainMm} mm</title></rect>`;svg+=`<text transform="translate(${x+8},220) rotate(35)" font-size="11">${label}</text>`});if(!rows.length)svg+='<text x="100" y="100">没有可用数据</text>';
 const el=$(id);el.setAttribute('viewBox',`0 0 ${width} 285`);el.style.minWidth=width+'px';el.innerHTML=svg;
}
function renderAreas(){const day=Number($('areaDay').value||0),regions=(snapshot.cityData?.regions||[]).filter(r=>r.parent===selectedParent&&r.kind==='county');$('areaCards').replaceChildren();let covered=0;for(const r of regions){const c=snapshot.cityData?.cities?.find(c=>c.code===r.weatherCode),d=c?.forecast?.daily?.[day],n=d?.rainMm??null,[g,color]=grade(n),el=node('button',null,'region'),icon=node('i'),text=node('span');icon.style.background=color;el.type='button';text.append(node('strong',r.name),node('small',d?d.date+' · '+(n==null?'雨量缺失':fmt(n)+' mm · '+g):'未取得该区县独立预报'));if(d)covered++;el.append(icon,text);el.addEventListener('click',()=>{selectedCity=r.id;$('citySelect').value=r.id;renderSupplement()});$('areaCards').append(el)}$('areaCoverage').textContent=selectedParent+'：'+covered+' / '+regions.length+' 个区县取得该日独立预报。色块依据源预报日雨量，不是预警范围；灰色表示缺失。'}
function renderSupplement(){
 const region=snapshot.cityData?.regions?.find(r=>r.id===selectedCity),city=snapshot.cityData?.cities?.find(c=>c.code===region?.weatherCode),obs=city?.observation,f=city?.forecast;
 $('cityTemperature').textContent=obs?.temperatureC==null?'—':fmt(obs.temperatureC)+' °C';$('cityHumidity').textContent=obs?.humidityPct==null?'—':fmt(obs.humidityPct)+' %';$('cityObserved').textContent=(region?region.parent+' / '+region.name:'地区')+'实况：'+date(obs?.observedAt)+(expired(obs?.observedAt)?'（缺失或已过期）':'')+' · 北京时间';
 $('citySource').href=city?.sourceUrl||'https://www.nmc.cn/publish/forecast/ASC/chengdu.html';
 $('predictedStart').textContent='无法确认';$('predictedDuration').textContent='无法确认';$('predictedEnd').textContent='无法确认';$('forecastDaily').replaceChildren();$('forecastTimeline').replaceChildren();
 $('forecastIssued').textContent='源预报发布时间：'+date(f?.sourceTime)+' · 北京时间';
 const usable=f&&f.timing==='current'&&Date.now()-new Date(f.sourceTime)<18*3600000&&!expired(snapshot.fetchedAt);
 $('forecastNotice').textContent=!f?'该地区未取得独立预测数据，未用邻近城市或演示数据替代。':!usable?'预测时效待核验：源发布时间异常、预测过期或采集快照过期。下面保留原始预报供核对，开始与持续估算暂停展示。':'开始、结束及持续时间是对逐三小时预报中第一段连续降雨的区间推算，非官方逐小时结论，也不代表必然发生暴雨。';
 if(usable){const w=f.window||{};if(w.status==='estimated'){$('predictedStart').textContent=date(w.startFrom)+' — '+date(w.startTo);if(w.endStatus==='estimated'){$('predictedEnd').textContent=date(w.endFrom)+' — '+date(w.endTo);$('predictedDuration').textContent=w.durationMinHours===0?'约小于 '+w.durationMaxHours+' 小时':'约 '+w.durationMinHours+' — '+w.durationMaxHours+' 小时'}}else if(w.status==='start_uncertain'){$('predictedStart').textContent='开始未知；'+date(w.firstRainAt)+' 预报有雨'}else if(w.status==='no_rain_in_window'){$('predictedStart').textContent='源预报窗口未示降雨'}}
 for(const d of f?.daily||[]){const el=node('article',null,'region');el.append(node('strong',d.date),node('p','白天 '+(d.day||'未知')+' / 夜间 '+(d.night||'未知')),node('small',d.rainMm==null?'预报雨量未提供':'源预报日雨量 '+fmt(d.rainMm)+' mm'));$('forecastDaily').append(el)}
 const horizon=Number($('forecastRange').value||168),rows=(f?.hours||[]).filter(r=>new Date(r.at)>Date.now()&&new Date(r.at)<=Date.now()+horizon*3600000),max=Math.max(1,...rows.map(r=>r.rainMm||0));for(const r of rows){const el=node('article',null,'forecast-slot');el.style.background=r.rainMm==null?'#f1f4f3':`rgba(56,189,248,${.08+.5*r.rainMm/max})`;el.append(node('strong',date(r.at)),node('small',r.rainExpected===true?'预报有雨':r.rainExpected===false?'晴 / 多云 / 阴':'天气未知'),node('small',r.rainMm==null?'雨量未提供':fmt(r.rainMm)+' mm'));$('forecastTimeline').append(el)}
 rainSvg('forecastChart',rows,'官方逐三小时降水预报，缺失值不填零');rainSvg('dailyChart',(f?.daily||[]).map(d=>({label:d.date,rainMm:d.rainMm})),'未来七天源预报日雨量');rainSvg('cityPastChart',city?.pastHours||[],'所选地区最近24小时实况');renderAreas();const a=snapshot.alertData,old=expired(a?.checkedAt);$('alertChecked').textContent='官方列表采集：'+date(a?.checkedAt)+' · 北京时间';$('alertList').replaceChildren();$('alertStatus').textContent=a?.status!=='ok'?'预警列表获取失败，当前预警状态无法确认。':old?'预警发布列表快照已过期，请查看官方原文。':a.items.length?'官方列表返回 '+a.items.length+' 条四川暴雨发布记录。':'当前官方列表未返回四川暴雨发布记录；不代表没有风险。';
 const colors={'红色':'#dc2626','橙色':'#ea580c','黄色':'#ca8a04','蓝色':'#2563eb'};for(const item of a?.items||[]){const el=node('article',null,'alert-record'),link=node('a',item.title);el.style.borderColor=colors[item.level]||'#64748b';link.href=item.sourceUrl;link.target='_blank';link.rel='noopener noreferrer';el.append(link,node('p','发布：'+date(item.issuedAt)+' · '+(item.level||'等级未提供')),node('small','是否解除或变更尚未核验，请查看原文'));$('alertList').append(el)}
}
const $=id=>document.getElementById(id);let snapshot=null,selected='',stations=[];
const fmt=v=>v==null?'缺少记录':Number(v).toFixed(1);
const date=v=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'未知';
const expired=v=>!v||Date.now()-new Date(v).getTime()>90*60000;
function grade(n){if(n==null)return['缺少记录','#d1d5db'];if(n===0)return['无降雨','#e5e7eb'];if(n<.1)return['微量降雨','#cffafe'];if(n<10)return['小雨','#67e8f9'];if(n<25)return['中雨','#38bdf8'];if(n<50)return['大雨','#2563eb'];if(n<100)return['暴雨','#4f46e5'];if(n<250)return['大暴雨','#9333ea'];return['特大暴雨','#581c87']}
const find=(p,key)=>p?.stations?.find(s=>s.key===key)?.valueMm??null;
function node(tag,text,cls){const el=document.createElement(tag);if(text!=null)el.textContent=text;if(cls)el.className=cls;return el}
function render(){if(!snapshot)return;const p=snapshot.products||{},daily=p['24h'],hourly=p['1h'],old=expired(snapshot.fetchedAt)||expired(daily?.observedAt)||expired(hourly?.observedAt),station=stations.find(s=>s.key===selected);
$('sourceStatus').textContent=snapshot.status==='error'?'采集失败，当前雨情无法确认':old?'真实数据快照 · 部分数据已过期，仅供历史查看':'中央气象台真实降水实况 · 定时采集';$('statusTitle').textContent=snapshot.status==='error'?'数据不可用':old?'请注意观测时效':'降水实况已更新';$('statusMessage').textContent=snapshot.message+' 抓取时间不等于观测时间。';$('collectedAt').textContent='最近采集：'+date(snapshot.fetchedAt)+' · 北京时间';$('observedAt').textContent='1小时产品：'+date(hourly?.observedAt)+(expired(hourly?.observedAt)?'（已过期）':'')+' / 24小时产品：'+date(daily?.observedAt)+(expired(daily?.observedAt)?'（已过期）':'');
const rain1=find(hourly,selected),rain24=find(daily,selected),[level,color]=grade(rain24);$('rain1').textContent=rain1==null?'—':fmt(rain1);$('rain24').textContent=rain24==null?'—':fmt(rain24);$('rain1Period').textContent=hourly?'源标注：'+hourly.sourcePeriod:'1小时产品不可用';$('rain24Period').textContent=daily?'源标注：'+daily.sourcePeriod:'24小时产品不可用';$('stationCount').textContent=daily?daily.stations.length:'—';$('dataAge').textContent=daily?Math.max(0,Math.floor((Date.now()-new Date(daily.observedAt))/60000)):'—';$('stationTitle').textContent=station?station.name+' · 国家级站点降水实况':'站点暂无记录';$('level').textContent=level+(expired(daily?.observedAt)?'（历史快照）':'');$('swatch').style.background=color;$('stationTotal').textContent=rain24==null?'该站在24小时产品中缺少记录':`过去24小时累计 ${fmt(rain24)} mm`;$('stationPeriod').textContent=daily?'源标注统计时段：'+daily.sourcePeriod:'统计时段未知';
$('regionCards').replaceChildren();for(const s of daily?.stations||[]){const[g,c]=grade(s.valueMm),b=node('button',null,'region'),i=node('i'),text=node('span');b.type='button';b.setAttribute('aria-pressed',String(s.key===selected));i.style.background=c;i.setAttribute('aria-hidden','true');text.append(node('strong',s.name),node('small',g+' · '+fmt(s.valueMm)+(s.valueMm==null?'':' mm')));b.append(i,text);b.addEventListener('click',()=>{selected=s.key;$('stationSelect').value=selected;render()});$('regionCards').append(b)}if(!daily?.stations?.length)$('regionCards').append(node('p','未获取四川站点记录，不能判断无降雨。','muted'));renderChart();renderSupplement()}
function renderChart(){const history=snapshot.history||[],values=history.map(p=>find(p,selected)),max=Math.ceil(Math.max(5,...values.filter(v=>v!=null))/5)*5;let svg='<title>所选站点最近24个发布时次的1小时实况雨量，缺失值不填零</title>';for(let j=0;j<=4;j++){const y=210-j*42;svg+=`<line x1="46" y1="${y}" x2="650" y2="${y}" stroke="#e8efec" stroke-dasharray="4 5"/><text x="34" y="${y+4}" text-anchor="end">${(max*j/4).toFixed(1)}</text>`}history.forEach((p,i)=>{const x=60+i*580/Math.max(history.length,1),v=values[i],h=v==null?0:v/max*168,label=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(p.observedAt));if(v==null||v===0)svg+=`<text x="${x+23}" y="199" text-anchor="middle">${v==null?'缺失':'0'}</text>`;else svg+=`<rect x="${x}" y="${210-h}" width="${Math.min(46,500/Math.max(1,history.length))}" height="${h}" rx="4" fill="#39a99a"><title>${label}：${v.toFixed(1)} mm</title></rect>`;if(i%Math.max(1,Math.ceil(history.length/8))===0)svg+=`<text x="${x+12}" y="236" text-anchor="middle">${label}</text>`});if(!history.length)svg+='<text x="330" y="110" text-anchor="middle">历史数据不可用</text>';$('chart').innerHTML=svg;$('tableBody').replaceChildren();history.forEach((p,i)=>{const row=node('tr');row.append(node('td',date(p.observedAt)),node('td',fmt(values[i])),node('td',p.sourcePeriod||'产品获取失败'));$('tableBody').append(row)});$('historyRange').textContent=history.length?date(history[0].observedAt)+' 至 '+date(history.at(-1).observedAt)+' · 北京时间':'暂无有效历史数据'}
async function load(){$('refresh').disabled=true;$('refresh').textContent='读取快照…';try{const r=await fetch('data/weather.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP');const d=await r.json();if(d.schemaVersion!==2||d.isDemo!==false||!d.products)throw Error('schema');snapshot=d;prepareCities();const map=new Map();for(const p of Object.values(d.products))for(const s of p.stations||[])map.set(s.key,s);stations=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));$('stationSelect').replaceChildren();if(!stations.length){const o=node('option','暂无站点数据');o.value='';$('stationSelect').append(o)}else{for(const s of stations){const o=node('option',s.name);o.value=s.key;$('stationSelect').append(o)}if(!stations.some(s=>s.key===selected))selected=stations[0].key}$('stationSelect').value=selected;render();$('fetchError').hidden=true}catch{snapshot=null;$('fetchError').hidden=false;$('sourceStatus').textContent='快照读取失败，当前雨情无法确认';$('statusTitle').textContent='数据读取失败';$('statusMessage').textContent='请查看官方原始页面。若下方仍有数字，它们是上次读取的旧快照。'}finally{$('refresh').disabled=false;$('refresh').textContent='重新读取'}}
$('parentSelect').addEventListener('change',()=>{selectedParent=$('parentSelect').value;selectedCity='';prepareCities();renderSupplement()});$('forecastRange').addEventListener('change',renderSupplement);$('areaDay').addEventListener('change',renderAreas);$('citySelect').addEventListener('change',()=>{selectedCity=$('citySelect').value;renderSupplement()});$('stationSelect').addEventListener('change',()=>{selected=$('stationSelect').value;render()});$('refresh').addEventListener('click',load);$('fontToggle').addEventListener('click',()=>{const active=document.body.classList.toggle('big');$('fontToggle').setAttribute('aria-pressed',String(active));$('fontToggle').textContent=active?'标准字号':'大字模式'});load();setInterval(()=>{if(snapshot)render()},60000);setInterval(load,5*60000);
